server:
  port: 10004
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eda-catalog?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cassandra:
    keyspace-name: "EdaCatalog"
    port: 9042
    local-datacenter: dc1
    schema-action: create_if_not_exists
    create-keyspace: true
    contact-points: localhost
  kafka:
    bootstrap-servers:
      - 127.0.0.1:19092
      - 127.0.0.1:19093
      - 127.0.0.1:19094
    consumer:
      group-id: edatutorial
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer