version: "3.8"

services:
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
  redis-server:
    image: redis
    ports:
      - "6379:6379"
  cassandra-server:
    image: cassandra
    container_name: cassandra-server
    environment:
      - CASSANDRA_CLUSTER_NAME=EdaCatalog
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=dc1