spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/template-server/schema;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true