### Health
GET {{host}}/index.html
Content-Type: text/html;charset=utf8;

### User Registration by GET
GET {{host}}/user/create/get?userId=test&password=1234&name=testName&email=kofc312@naver.com
Content-Type: application/json

### User Registration by POST
POST {{host}}/user/create
Content-Type: application/json

{
  "name": "testName",
  "userId": "te1st",
  "email": "kofc312@naver.com",
  "password": "1234"
}